version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://localhost:3000
      - DB_TYPE=postgres
      - POSTGRES_URL=postgresql+asyncpg://user:password@postgres:5432/dbname
      - MONGODB_URL=mongodb://mongo:27017/dbname
      - JWT_SECRET=supersecretjwtkey
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=storage
      - S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - BUCKET_NAME=mybucket
      - MOCKUP_SERVICE_TYPE=opencv
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"  # Optional: management console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

